# CI and PR build script
#
# There should be no deep magic here. The developer experience and CI experience
# must remain as close to one another as possible.
#
# Developer experience:
#   npm install
#   (make changes)
#   npm test
#   vsce package
#   (give VSIX to someone for buddy testing)
trigger:
  branches:
    include:
    - feature/githubActions

pr:
- feature/githubActions
# no `pr` keyword because we want all PRs to run this

pool:
  vmImage: ubuntu-16.04

steps:
# for convenience, we tag CI-produced packages with a version number
# pointing to the commit which was built. for PRs, also include the PR #.
- bash: |
    PACKAGE_VERSION=$(node -p "require('./package.json').version")
    npm --no-git-tag-version version $PACKAGE_VERSION
    echo "$PACKAGE_VERSION" > version.txt
  displayName: Set version number of package and build

- template: common-steps.yml
