# CI and PR build script
#
# There should be no deep magic here. The developer experience and CI experience
# must remain as close to one another as possible.
#
# Developer experience:
#   npm install
#   (make changes)
#   npm test
#   vsce package
#   (give VSIX to someone for buddy testing)
trigger:
  branches:
    include:
    - master

# no `pr` keyword because we want all PRs to run this

name: $(BuildDefinitionName)_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
# source branch is equal to master
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - template: common-steps.yml
    parameters:
      jobName: CI
# Only use PR if this is the build reason
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - template: common-steps.yml
    parameters:
      jobName: PR
