# Release build script
#
# Uses the common build logic, but also gains capabilities related to releasing the product.

# Only trigger manually
trigger:
  batch: true
  branches:
    include:
    - releases/*
pr: none

name: $(BuildDefinitionName)_$(Build.SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
  # do all the normal build stuff
  - template: common-steps.yml
    parameters:
      jobName: Release_CI
# upload the package only if variable 'UploadPackage' is true
  - ${{ if eq(variables['UploadPackage'], 'true') }}:
    - template: upload-package.yml